// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrtRbO4Q7M7JhCoFZjRp_CQGZh830VGhw',
    appId: '1:980632436532:web:c4d6f03a1093aa2700af61',
    messagingSenderId: '980632436532',
    projectId: 'getxfirebase-34c80',
    authDomain: 'getxfirebase-34c80.firebaseapp.com',
    storageBucket: 'getxfirebase-34c80.appspot.com',
    measurementId: 'G-ZX5PJJTCV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWcyc4zTIvWYz-1Hrq5aifURDkN3kkdI8',
    appId: '1:980632436532:android:87def7d3ffdf9f9400af61',
    messagingSenderId: '980632436532',
    projectId: 'getxfirebase-34c80',
    storageBucket: 'getxfirebase-34c80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVV8jbXTtx7-xTYkuYFHmW2HUBUQ5hW9E',
    appId: '1:980632436532:ios:0e5a38332063bebc00af61',
    messagingSenderId: '980632436532',
    projectId: 'getxfirebase-34c80',
    storageBucket: 'getxfirebase-34c80.appspot.com',
    iosClientId: '980632436532-vfctd56j8tqiad7hq97eov5a94kv470t.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxFirebase',
  );
}
